language: node_js
node_js:
  - "4.0.0"
before_install:
     - npm update -g npm
     - npm install grunt-cli
     - npm install bower
     - npm install gh-pages-travis
install:
    - npm install
    - bower update
before_script:
    - grunt build
    - npm run gh-pages-travis
env:
  global:
    - SSH_KEY="f2870c2b22c455c0aeaa5900c56af22a3df074aa"
    - GIT_NAME="Ravi Chandra Ravulapati"
    - GIT_EMAIL="ravichandra480@gmail.com"
    - SOURCE_DIR="profile"
    - DEPLOY_BRANCH="gh-pages"
