language: node_js
node_js:
  - "4.0.0"
before_install:
     - npm update -g npm
     - npm install grunt-cli
     - npm install bower
install:
    - npm install
    - bower update
before_script:
    - grunt build
