language: node_js
node_js:
  - "4.0.0"
before_install:
     - npm update -g npm
     - npm install grunt-cli
     - npm install bower
install:
    - npm install
    - bower update
branches:
  only:
    - gh-pages
before_script:
    - grunt build
    - git config --global user.email "ravichandra480@gmail.com"
    - git config --global user.name "Ravi Chandra Ravulapati"
    - git remote rm origin
    - git remote add origin https://user:f2870c2b22c455c0aeaa5900c56af22a3df074aa@github.com/user/repo.git
script: npm run deploy
env:
  global:
    secure: encrypted-github-token
